---

- name: 'Get current proftpd version'
  shell: proftpd --version | cut -d ' ' -f3
  register: current_proftpd_version
  ignore_errors: true
  changed_when: false
  tags: ['skip_ansible_lint'] #skip ansible lint as shell is required here

- name: Set fact current_duplicity_version
  set_fact:
    current_proftpd_version: '{{current_proftpd_version.stdout}}'

- name: 'Set proftpd version fact'
  set_fact:
    proftpd_version: "{{ proftpd_download_url | basename | replace('proftpd-', '') | replace('.tar.gz', '') }}"

- include: install.yml
  tags: ['proftpd-install']

#No modules for compiled version...
#- include: modules.yml
#  when: _proftpd_installed.changed

- include: configure.yml
  tags: ['proftpd-configure']

- include: ssl.yml
  tags: ['proftpd-ssl']

- name: start proftpd
  service:
    name: 'proftpd'
    state: started
    enabled: yes
  changed_when: false # to make it idempotence


